
version: '3'
services:

  postgres:
    container_name: 'postgres_notes'
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: notes_db
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - 'notesdata:/var/lib/postgresql/data/'

volumes:
    notesdata:



